language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-webapp-kit' ]; then cd .. && eval "mv $currentfolder generator-webapp-kit" && cd generator-webapp-kit; fi
